/*
 * The MIT License
 *
 * Copyright 2014 Tavo.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package BD;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Tavo
 */
public class BDUI extends javax.swing.JFrame 
{

    /*
     * Variables Globables
     */
    String Hostname;
    String Puerto;
    String Database;
    String Username;
    String Password;
    Connection connection;
    DefaultListModel Lista1;//Lista usada para poblar la Jlist listaAtributos1
    DefaultListModel Lista2;//Lista usada para poblar la JList ListaAtributos2
    String TablaActual;//Nombre de la tabla seleccionada
    DefaultTableModel ModeloTabla;//modelo que se le asignara a la tablaDatos
    
    /**
     * Creates new form BDUI
     */
    public BDUI() 
    {
        initComponents();
        Hostname = "";
        Puerto = "";
        Database = "";
        Username = "";
        Password = "";
        connection = null;
        Vistas.pack();//para que la ventana no aparezca pequeña
        Filtros.pack();//para que la ventana (jframe) no aparezca pequeña
        Lista1 = new DefaultListModel();
        Lista2 = new DefaultListModel();
        listaAtributos1.setModel(Lista1);
        listaAtributos2.setModel(Lista2);
        TablaActual = "";        
        ModeloTabla = new DefaultTableModel();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vistas = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        comboBoxBasedatos = new javax.swing.JComboBox();
        botonMostrarTablas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboBoxTablas = new javax.swing.JComboBox();
        botonMostrarAtributos = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAtributos1 = new javax.swing.JList();
        botonAgregarAtributo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAtributos2 = new javax.swing.JList();
        botonQuitarAtributo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        botonAceptar = new javax.swing.JButton();
        botonAgregarFiltro = new javax.swing.JButton();
        Filtros = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFieldHostname = new javax.swing.JTextField();
        textFieldPuerto = new javax.swing.JTextField();
        textFieldBasedatos = new javax.swing.JTextField();
        textFieldUsuario = new javax.swing.JTextField();
        botonIngresar = new javax.swing.JButton();
        textFieldPassword = new javax.swing.JPasswordField();
        botonCancelar = new javax.swing.JButton();

        jLabel7.setText("Seleccione Basedatos:");

        botonMostrarTablas.setText("Mostrar Tablas");
        botonMostrarTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTablasActionPerformed(evt);
            }
        });

        jLabel8.setText("Tablas:");

        botonMostrarAtributos.setText("Mostrar Atributos");
        botonMostrarAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarAtributosActionPerformed(evt);
            }
        });

        jLabel9.setText("Atributos:");

        listaAtributos1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaAtributos1);

        botonAgregarAtributo.setText("-->");
        botonAgregarAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarAtributoActionPerformed(evt);
            }
        });

        listaAtributos2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaAtributos2);

        botonQuitarAtributo.setText("<--");
        botonQuitarAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarAtributoActionPerformed(evt);
            }
        });

        jLabel10.setText("Tuplas:");

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaDatos);

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonAgregarFiltro.setText("Agregar Filtro");
        botonAgregarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VistasLayout = new javax.swing.GroupLayout(Vistas.getContentPane());
        Vistas.getContentPane().setLayout(VistasLayout);
        VistasLayout.setHorizontalGroup(
            VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(VistasLayout.createSequentialGroup()
                        .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxBasedatos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMostrarTablas)
                            .addComponent(botonMostrarAtributos)))
                    .addComponent(jLabel10)
                    .addGroup(VistasLayout.createSequentialGroup()
                        .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAceptar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAgregarAtributo)
                            .addComponent(botonQuitarAtributo))
                        .addGap(22, 22, 22)
                        .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregarFiltro))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VistasLayout.setVerticalGroup(
            VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VistasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxBasedatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMostrarTablas))
                .addGap(18, 18, 18)
                .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonMostrarAtributos)))
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1))
                    .addGroup(VistasLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(botonAgregarAtributo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonQuitarAtributo)))
                .addGap(18, 18, 18)
                .addGroup(VistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptar)
                    .addComponent(botonAgregarFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout FiltrosLayout = new javax.swing.GroupLayout(Filtros.getContentPane());
        Filtros.getContentPane().setLayout(FiltrosLayout);
        FiltrosLayout.setHorizontalGroup(
            FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        FiltrosLayout.setVerticalGroup(
            FiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese la información para conectar a Postgresql.");

        jLabel2.setText("Hostname:");

        jLabel3.setText("Puerto:");

        jLabel4.setText("Basedatos:");

        jLabel5.setText("Usuario:");

        jLabel6.setText("Contraseña:");

        textFieldHostname.setText("localhost");

        textFieldPuerto.setText("5432");

        textFieldBasedatos.setText("postgres");

        textFieldUsuario.setText("postgres");

        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        textFieldPassword.setText("admin");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFieldHostname)
                                        .addComponent(textFieldPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(textFieldBasedatos, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textFieldPassword))))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(botonIngresar)
                        .addGap(32, 32, 32)
                        .addComponent(botonCancelar)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldBasedatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIngresar)
                    .addComponent(botonCancelar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        Hostname = textFieldHostname.getText();
        Puerto = textFieldPuerto.getText();
        Database = textFieldBasedatos.getText();
        Username = textFieldUsuario.getText();
        Password = textFieldPassword.getText();
        conectarPostgresql();
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonMostrarTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTablasActionPerformed
        if(comboBoxBasedatos.getItemCount() > 0)
        {
            mostrarTablas();
        }
    }//GEN-LAST:event_botonMostrarTablasActionPerformed

    private void botonMostrarAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarAtributosActionPerformed
        if(comboBoxTablas.getItemCount() > 0)
        {
            Lista1.clear();
            Lista2.clear();
            listaAtributos1.updateUI();
            listaAtributos2.updateUI();
            ModeloTabla = new DefaultTableModel();
            tablaDatos.setModel(ModeloTabla);
            tablaDatos.updateUI();
            mostrarAtributos();
        }
    }//GEN-LAST:event_botonMostrarAtributosActionPerformed

    private void botonAgregarAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarAtributoActionPerformed
        //primero verificamos que la lista no este vacia para poder agregar un atributo a la otra lista
        if(!Lista1.isEmpty())
        {
            int[] listaIndices1 = listaAtributos1.getSelectedIndices();
            for(int i = 0; i < listaIndices1.length; i++)
            {
                //System.out.println("Se va a mover el atributo: " + Lista1.getElementAt(listaIndices1[i]));
                Lista2.addElement(Lista1.getElementAt(listaIndices1[i]));
                Lista1.removeElementAt(listaIndices1[i]);
                listaAtributos1.updateUI();
                listaAtributos2.updateUI();
            }
        }
    }//GEN-LAST:event_botonAgregarAtributoActionPerformed

    private void botonQuitarAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarAtributoActionPerformed
        //primero validamos que la lista este poblada antes de quitar un atributo
        if(!Lista2.isEmpty())
        {
            int[] listaIndices2 = listaAtributos2.getSelectedIndices();
            for(int i = 0; i < listaIndices2.length; i++)
            {
                Lista1.addElement(Lista2.getElementAt(listaIndices2[i]));
                Lista2.removeElementAt(listaIndices2[i]);
                listaAtributos1.updateUI();
                listaAtributos2.updateUI();
            }
        }
    }//GEN-LAST:event_botonQuitarAtributoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(!Lista2.isEmpty())
        {
            mostrarTuplas();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonAgregarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarFiltroActionPerformed
        Filtros.setVisible(true);
    }//GEN-LAST:event_botonAgregarFiltroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BDUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Filtros;
    private javax.swing.JFrame Vistas;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAgregarAtributo;
    private javax.swing.JButton botonAgregarFiltro;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonMostrarAtributos;
    private javax.swing.JButton botonMostrarTablas;
    private javax.swing.JButton botonQuitarAtributo;
    private javax.swing.JComboBox comboBoxBasedatos;
    private javax.swing.JComboBox comboBoxTablas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaAtributos1;
    private javax.swing.JList listaAtributos2;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField textFieldBasedatos;
    private javax.swing.JTextField textFieldHostname;
    private javax.swing.JPasswordField textFieldPassword;
    private javax.swing.JTextField textFieldPuerto;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables

    /*
     * Procedimiento usado para conectar a la base de datos, esta conexión se hace para obtener los nombres de las bases de datos actuales.
     * La conexión se guarda en la variable 'connection'
     * Nota: la cadena de conexión no tiene nombre de BD a conectarse
     */
    private void conectarPostgresql()
    {
        try
        {
            Class.forName("org.postgresql.Driver");
            String cadenaConexion = "jdbc:postgresql://" + Hostname + ":" + Puerto + "/";// + Database;
            connection = DriverManager.getConnection(cadenaConexion, Username, Password);
            JOptionPane.showMessageDialog(this, "Conexión exitosa.");
            mostrarVistas();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error en la conexión.");
        }
    }
    
    /*
     * Procedimiento para poblar el JComboBox comboBoxBasedatos con los nombres de la bases de datos de la actual conexión
     */
    private void mostrarVistas()
    {
        Vistas.setVisible(true);
        try
        {
            Statement query = connection.createStatement();
            ResultSet resultado = query.executeQuery("SELECT datname FROM pg_database WHERE datistemplate = false;");
            while(resultado.next())
            {
                comboBoxBasedatos.addItem(resultado.getObject(1));
            }
        }
        catch(Exception e){System.err.println("error en vistas");}
    }
    
    /*
     * Procedimiento usado para poblar el comboBoxTablas con las tablas de la base de datos seleccionada
     * Primero cerramos la conexión anteriormente creado, pues se necesita una nueva que contenga en la cadena de conexión el nombre de la BD
     */
    private void mostrarTablas()
    {
        if(!comboBoxBasedatos.getSelectedItem().equals(""))
        {
            try
            {
                connection.close();
                String cadenaConexion = "jdbc:postgresql://" + Hostname + ":" + Puerto + "/" + comboBoxBasedatos.getSelectedItem().toString();
                connection = DriverManager.getConnection(cadenaConexion, Username, Password);
                                
                Statement query = connection.createStatement();
                ResultSet rs = query.executeQuery("SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = 'public';");
                while(rs.next())
                {
                    comboBoxTablas.addItem(rs.getObject(1));
                }
            }
            catch(Exception e){System.err.println("error en mostarTablas");}
        }
    }
    
    /*
     * Procedimiento para poblar la primera lista de atributos 'listaAtributos1' con los atributos de la tabla seleccionada
     * Usamos la conexión creado con la BD, del proc. mostrarTablas()
     * Llenamos un DefaultListModel 'Lista1' el cual desupués asignamos al JList
     */
    private void mostrarAtributos()
    {
        if(!comboBoxTablas.getSelectedItem().equals(""))
        {
            try
            {
                Statement query = connection.createStatement();
                TablaActual = comboBoxTablas.getSelectedItem().toString();
                ResultSet rs = query.executeQuery("SELECT column_name FROM information_schema.columns WHERE table_name = '" + TablaActual + "';");
                Lista1.clear();
                while(rs.next())
                {
                    Lista1.addElement(rs.getObject(1));
                }
            }
            catch(Exception e){System.err.println("error en MostrarAtributos");}
        }
    }
    
    /*
     * Procedimiento usado para poblar la JTable tablaDatos con los datos de los atributos seleccionados
     * Primero hacemos el query a la BD y con el ResultSet poblamos dicha tabla
     */
    private void mostrarTuplas()
    {
        try
        {
            Statement query = connection.createStatement();
            String cadenaQuery = "SELECT ";
            for(int i = 0; i < Lista2.getSize(); i++)
            {
                if(i > 0)
                {
                    cadenaQuery += ", " + Lista2.getElementAt(i);
                }
                else
                {
                    cadenaQuery += Lista2.getElementAt(i);
                }
            }
            cadenaQuery += " FROM " + TablaActual + ";";
            //System.out.println("Query: " + cadenaQuery);
            ResultSet rs = query.executeQuery(cadenaQuery);
            
            ResultSetMetaData meta = rs.getMetaData();
            String cols[] = new String[meta.getColumnCount()];
            for(int j = 0; j < cols.length; ++j)
            {
                cols[j] = meta.getColumnLabel(j+1);
            }
            ModeloTabla.setColumnIdentifiers(cols);
            while(rs.next())
            {
                Object data[] = new Object[cols.length];
                for(int k = 0; k < data.length; ++k)
                {
                    data[k] = rs.getObject(k+1);
                }
                ModeloTabla.addRow(data);
            }
            tablaDatos.setModel(ModeloTabla);
        }
        catch(Exception e){System.err.println("error en mostrarTuplas");}
    }
}